config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
    sessions: 'users/sessions'

    }
  devise_scope :admin do
    get "admins/users/list",
    to: "admins/sessions#list",
    as: "users_list"
  end

  resources :zombies do
    resources :brains

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
  root to: 'zombies#index'
  get '/sexto/cerebros', to: 'brains#index', as: 'brains'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "App :v" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>


  <body>

    <div class="top-bar foundation-5-top-bar">
      <div class="top-bar-title">
        <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
          <button class="menu-icon" type="button" data-toggle></button>
        </span>
        <strong>Zombie App</strong>
      </div>
      <div id="responsive-menu">
        <div class="top-bar-left">
          <ul class="dropdown vertical medium-horizontal menu" data-responsive-menu="drilldown medium-dropdown" data-auto-height="true" data-animate-height="true">
            <li>
              <a href="#">Menu Zombies</a>
              <ul class="menu">
                <li><%= link_to 'Lista Zombie', zombies_path %></li>
                <li><%= link_to 'Nuevo Zombie', new_zombie_path %></li>
                <%if admin_signed_in?%>
                 <li><%= link_to 'Lista usuarios', new_admin_session_path %></li>
                <%end%>
                
              </ul>
            </li>
          </ul>
        </div>
        <div class="top-bar-right">
          
            <%if admin_signed_in?%>
         <strong>Bienvenido(a) <%= current_admin.email%> </strong>
          <div>
            <strong><%= link_to "Cerrar sesíon", destroy_admin_session_path, method: :delete%></strong>
          </div>
          <div>
            <strong><%=link_to "Editar perfil", edit_admin_registration_path%></strong>
          </div>
          
           <%else%>
          <%if user_signed_in?%>
          <strong>Bienvenido(a) <%= current_user.email%> </strong>
          <div>
            <strong><%= link_to "Cerrar sesíon", destroy_user_session_path, method: :delete%></strong>
          </div>
          <div>
            <strong><%=link_to "Editar perfil", edit_user_registration_path%></strong>
          </div>
        <%else%>
          
          <div>
            <strong><%=link_to "login",new_user_session_path%></strong>
          </div> 
          <div>
            <strong><%=link_to "Registrarse",new_user_registration_path%></strong>
          </div>
          <%end%>
          
          <%end%>
          
        </div>

      </div>
    </div>

    <%= yield %>
    <%if notice%>
    <p class="alert alert-success"><%=notice%></p>
    <%end%>
    <%if alert %>
    <p class="alert alert-danger"><%=alert%></p>
    <%end%>
  </body>
</html>